### ISSUE TITLE
clean up code to use vector/matrix notation

### ISSUE THREAD

**Issue by gkiehne** [quantopian/quantopian-algos#2]
Some progress toward using vector/matrix notation in code below.  Probably more work to be done.

---
# 
# Algorithm based on this publication:
# http://alphapowertrading.com/papers/OnLinePortfolioSelectionMovingAverageReversion.pdf
# 

import numpy as np

def initialize(context):

```
context.stocks = [sid(8554),sid(19920),sid(22739)]
context.price = {}
context.x_tilde_s = {}
context.b_t_s = {}
context.eps = 1.1
```

def handle_data(context,data):

```
x_bar = 0.0
m = len(context.stocks)
x_tilde = np.zeros(m)
b_t = np.zeros(m)
b = np.zeros(m)

# find relative moving average price for each security
for stock in context.stocks:
    price = data[stock].price
    x_tilde_s = float(data[stock].mavg(3))/price
    if context.portfolio.positions_value > 0.0:
        b_t_s = context.portfolio.positions[stock].amount * price
        b_t_s = b_t_s/context.portfolio.positions_value
    else:
        b_t_s = 1.0/m
    x_bar = x_bar + x_tilde_s

x_bar = x_bar/m #average predicted relative price

#convert to vectors
i = 0
for stock in context.stocks:
    x_tilde[i] = x_tilde_s
    b_t[i] = b_t_s
    i = i+1

sq_norm = (np.linalg.norm((x_tilde-x_bar)))**2
dot_prod = np.dot(b_t,x_tilde)

log.debug(sq_norm)
log.debug(dot_prod)

lam = max(0,(context.eps-dot_prod)/sq_norm)

b = b_t + lam*(x_tilde-x_bar)

log.debug(b)
```

**Comment by gkiehne** [comment]
Hello Thomas,

I assigned you to this issue since I couldn't figure out how to send a github notification easily.

I updated the code.  Still pretty messy, but I made some headway in sorting out how to fill vectors for subsequent linear algebra operations.  Not sure it is the best approach...I'm open to advice.

Grant

**Comment by twiecki** [comment]
OK, looks good. I'll get to this probably on Thurs. I assume you uploaded the most recent version?

**Comment by gkiehne** [comment]
Thomas,

Yes, the uploaded code is an update.  The main thing to look at is how I create and fill the vectors.  If there is a better way, please let me know.

**Comment by gkiehne** [comment]
Hello Thomas,

The order problem is now fully resolved (see https://www.quantopian.com/posts/help-with-order-problem).  So, at some point, I'll get back to seeing if I can complete the first phase of this project - the simple OLMAR algorithm based on a moving average over a single window.

Grant

**Comment by twiecki** [comment]
Hi Grant,

I took a stab at it, see if it makes sense to you. There is still a problem with Lambda though which I'm not sure about. One thing which wasn't obvious was that x_bar is actually the mean of x_tilde (they just write in a weird way).

I also vectorized the rebalance_portfolio function.

**Comment by gkiehne** [comment]
Thanks Thomas,

Please see my comments here:

https://www.quantopian.com/posts/on-line-portfolio-selection-from-grant-k

I'll copy and paste the code into Quantopian and give it a try.

Grant
